language: c
matrix:
        allow_failures:
                - os: linux
                  dist: xenial
        include:
                - name: "Linux autotools build"
                  os: linux
                  dist: trusty
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                  script: ./autogen.sh && ./configure --prefix=`pwd`/tempinstall && make && make install && make dist && tar -tzvf gnusim8085*.tar.*

                - name: "Linux meson build"
                  os: linux
                  dist: xenial
                  addons:
                          apt:
                                  packages:
                                          - libgtksourceview-3.0-dev
                                          - gettext
                                          - discount
                                          - python3-pip
                                          - python3-setuptools
                  install:
                          - pip3 install --user meson==0.37.0
                          - export PATH=$PATH:~/.local/bin
                  script: rm -rf builddir && meson --prefix=`pwd`/mesoninstall builddir && cd builddir && ninja dist && cd ..

                - name: "macOS autotools build"
                  os: osx
                  before_install:
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - ./autogen.sh
                          - ./configure --prefix=`pwd`/tempinstall
                          - make install
                          - otool -L tempinstall/bin/gnusim8085
                          - make dist
                          - tar -tzvf gnusim8085*.tar.*

                - name: "macOS meson build"
                  os: osx
                  before_install:
                          - brew install --build-from-source gdk-pixbuf --with-included-loaders=png
                          - brew bundle
                          - brew link --force gettext
                  script:
                          - rm -rf macosdist
                          - meson --prefix=`pwd`/macosdist/GNUSim8085.app --bindir=Contents/MacOS --datadir=Contents/Resources --localedir=Contents/Resources/locale --mandir=Contents/SharedSupport -Dbuild-macos-app=true macosdist
                          - cd macosdist && ninja install && shasum -a 256 *.zip && cd ..
                          #- otool -L macosdist/GNUSim8085.app/Contents/MacOS/gnusim8085
                          #- strings macosdist/GNUSim8085.app/Contents/MacOS/gnusim8085|sort -u
                          - otool -L macosdist/GNUSim8085.app/Contents/libs/*.dylib
                          #- otool -L macosdist/GNUSim8085.app/Contents/libs/gdk-pixbuf-2.0/2.10.0/loaders/*.so
                          #- rm -rf distdir
                          #- meson distdir
                          #- cd distdir && meson configure && ninja dist && cat meson-dist/*.sha256sum && cd ..
                  deploy:
                          provider: releases
                          api_key:
                                  secure: Zd1gkmesg5kOHEWnruhzB/PiPMmYgYptS+ra+1Wz00Oy0B0gNftKcsNoHLxmCx2P3atNSiqxYHjlw4Dg9rbckKLMpU096+Bs7AWmJG30L5NFOsy8z2HRCcM+513MCF2dd3d/R/cIPEOTr9GzMMHQCpQkExq7JGAIJ3n53hg+J50iU12ZKC+kBuscMJvl5QaBtci+1We/6ADG4zXHbhAY6nyxE9ZWg71GYFPFtaM6Vv3BrVmD1M/dKEqwn+1D2KFl3nVpueXxPUpriZT7z4RFRM4yK6ORcLGGMu6jc3CQ+gyLyg9d/SY2o8/VkotEzIBZo27EMZvFlX2JFHSyoq7BaaIn41JPfrwgTYtTH1vWX53eSk3ERuiwlQdxVmnqUwPMQx76gE6OvWzub5Pn10R+XbRu9aVUSMtex7I3ie3uP7oAsg7twy3+vxiqEwJuxy/tw6a/zecca6sBaZ5N8XmOjMLSU9UON8NS1n0Iaf88JH+sMgOG0I+Ud6RchKo5k4wDhkq2n1/nMG1ChA1426EtPK9rs7+XMXD4omMZ8Jqtsn0uqnApJxWJPdlzt8Sy3UVztW3eWM4dV5WvPiySrfL01Q7w4Caqf4M8AZc9JgjqWOADuDdYY+gVuATvjVkWd+MjaKSGbH6evS0ue8DTeV8yvw3YEDxNSkj7hoYrkwChhLw=
                          file_glob: true
                          file:
                                  - macosdist/gnusim8085*.zip
                                    #- distdir/meson-dist/gnusim8085*.tar.xz
                          draft: true
                          prerelease: true
                          skip_cleanup: true
                          on:
                                  repo: GNUSim8085/GNUSim8085
                                  tags: true
